### ISSUE TITLE
How can I play pause from C# code?

### ISSUE THREAD

**Issue by wezzix** [aleab/toastify#108]
Toastify is great, thank you for your hard work!
I'm tired of maintaining my own API for basic spotify actions which they constantly break, and would like to shift in toastify source. **I'm looking specifically for a code snippet, test, class or similar of how to play/pause** in code. Could you please point me in the right direction? Thanks!

**Comment by aleab** [comment]
Hi @wezzix 

Assuming a Windows-only use-case, the solution can be as simple as emulating the media virtual keys (*VK_MEDIA_PLAY_PAUSE* in your case) using e.g. the [`keybd_event`](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-keybd_event) function.

```c#
[DllImport("user32.dll")]
internal static extern void keybd_event(VirtualKeyCode bVk, byte bScan, uint dwFlags, int dwExtraInfo);

[DllImport("user32.dll")]
internal static extern uint MapVirtualKey(uint uCode, MapVirtualKeyType uMapType);

// https://docs.microsoft.com/en-gb/windows/desktop/inputdev/virtual-key-codes
internal enum VirtualKeyCode : byte
{
    VK_MEDIA_PLAY_PAUSE = 0xB3
}

const uint KEYEVENTF_EXTENDEDKEY = 1;
const uint KEYEVENTF_KEYUP = 2;

internal enum MapVirtualKeyType : uint
{
    MAPVK_VK_TO_VSC    = 0,
    MAPVK_VSC_TO_VK    = 1,
    MAPVK_VK_TO_CHAR   = 2,
    MAPVK_VSC_TO_VK_EX = 3,
    MAPVK_VK_TO_VSC_EX = 4
}

public void PlayPause()
{
    uint scanCode = 0x22;
    // uint scanCode = MapVirtualKey((uint)VirtualKeyCode.VK_MEDIA_PLAY_PAUSE, MapVirtualKeyType.MAPVK_VK_TO_VSC);

    keybd_event(VirtualKeyCode.VK_MEDIA_PLAY_PAUSE, (byte)scanCode, KEYEVENTF_EXTENDEDKEY | 0, 0);
    // Thread.Sleep ?
    keybd_event(VirtualKeyCode.VK_MEDIA_PLAY_PAUSE, (byte)scanCode, KEYEVENTF_EXTENDEDKEY | KEYEVENTF_KEYUP, 0);
}
```

I can't remember why exactly, but I ditched this solution myself because it wasn't working consistently, so I ended up using [`PostMessage`](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-postmessagea) instead.
You can find a short code snippet here: JohnnyCrazy/SpotifyAPI-NET#231. Your `PlayPause` method would look something like this:
```c#
private const long cmdPlayPause = 0x000E0000L;
public void PlayPause()
{
    PostMessage(spotifyHWnd, WM_APPCOMMAND, IntPtr.Zero, (IntPtr)cmdPlayPause);
}
```

**Comment by wezzix** [comment]
keybd_event did not work unless Spotify was in foreground. So PostMessage it is. My smart home now works again. Thank you kindly for your help!
