### ISSUE TITLE
making artist and title syntax clearer

### ISSUE THREAD

**Issue by Vankog** [aleab/toastify#11]
Looking at the [network graph's commits by other toastify devs](https://github.com/nachmore/toastify/network) I am not the only one who thinks that the order of title and artist matters alot.

Everyone prefers another order, but I for myself am constantly struggling to remember which one Toastify uses. I actively have to memorize it (and fail in doing so over and over again). Therefore I have an easily implementable proposal to make it unambiguous.
Regardless of the order (which obviously could also be configurable in the future), I'd rather like to add key clues to "Title1" (aka artist) and "Title2" (aka track title) for better understanding.

Instead of the current plain:
```
    Artist name
    Track name
```

How about
```
    Artist name:
    Track name
```
or
```
    Artist name:
    "Track name"
```
or
```
    Track name
    by Artist name
```
or something alike.
Those clues would give quite valuable insight about the syntax of the toast and therefore are crucial for intuitive recognition by the user.

**Comment by Vankog** [comment]
I think something alike this (dirty hack) might be it? #12 
As already told, I have no .NET env. so this is just an educated blind guess.

**Comment by aleab** [comment]
Believe it or not, but for all this time I though I had already changed the track and artist name order to match the one used by Spotify. Turns out I didn't! Ahhahah! 😅

I like your suggestions and I personally prefer the third one, because I do not really like using a colon after the artist name (it might not be immediately visible if it is longer the the width of the toast), and I'd rather not use quotation marks if possible (personal preference).

Also, what do you think of making the "by" visually different (different color/different opacity/italics) from the artist name? Do you think it's worthwhile?
If not, I'll be glad to merge your commit if you change it using your third suggestion.

At some point in the future, I'll probably let the order of Track and Artist name be customizable and use your second and third suggestions for the two possible cases.

**Comment by Vankog** [comment]
OK, switched the two. I also prefer this order.

Hm... not sure about the formatting of "by". Need to see it for myself.
But we can always change that later on.

**Comment by aleab** [comment]
For the moment I'll just merge your changes.

**Comment by Vankog** [comment]
very good :-)
