### ISSUE TITLE
Bug: Show-Toast hot-key shows toast only for a fraction of a second

### ISSUE THREAD

**Issue by Vankog** [aleab/toastify#25]
The toast only shows up for a fraction of a second when using the Show Toast hot-key.
However, the toast shows correctly on automatic or forced track changes, play/pause or volume control hot-key.

Restarting Toastify does not change this behaviour, nor does changing the hot-key.

Version: Custom build from performance issue.

**Comment by aleab** [comment]
Unfortunately I couldn't reproduce this behaviour in my tests, right now. However, I already knew of this bug and I've never been able to discover what causes it. Strangely, though, restarting Toastify always fixes it for me.

I've changed part of the code that involves the fading-in/out of the Toast just now, because it was kind of messy. I'll test it for a couple of days to see if it fixes this strange behaviour.

**Comment by Vankog** [comment]
I was already afraid that this is something hard to pinpoint.
Now, after a restart of the system it works fine again. It really seems .NET might be the root cause of all of this. Maybe there are some platform bugs with systems using hibernation and/or high memory load.

**Comment by aleab** [comment]
Fixed it!
