### ISSUE TITLE
Mouse thumb buttons (XButton1/Mouse4 and XButton2/Mouse5) in hotkey combinations

### ISSUE THREAD

**Issue by gahujipo** [aleab/toastify#36]
Hi there, 
I read in your release notes that with the latest release it should be possible to use those buttons on the mouse. Until now i always used the Logitech SetPoint Control Panel to trigger a hotkey combination when i pressed the mouse. Those hotkeys were picked up by Toastify and it did it's work after that. 

But how can I set those buttons as hotkeys in Toastify? I am using a [Logitech M500](https://www.logitech.com/it-it/product/corded-mouse-m500). That kind of mouse is suitable, right?

**Comment by aleab** [comment]
It should be, yeah.
Have you already tried to use them in the Hotkeys section of the settings or not?

![Hotkeys Settings](https://vgy.me/RW3DX2.png)

Just click on the small text box near "Press a Key" to have it focused and then press the mouse button.

**Comment by gahujipo** [comment]
Yep. That is exactly what I tried. Nothing happens when i click the buttons while having the text box focused (clicked once). Does that work for you?

**Comment by Blazeflack** [comment]
It works for me with my Razer Naga Hex v2. When I bind one of my side buttons the text in the keybind box says "D#" where # is a number between 1 and 7 both included.

**Comment by aleab** [comment]
@gahujipo, yes, it does work on my side with a ROG Gladius.
I have a couple of ideas on what might be the issue for you; tomorrow I'll post a test release here with extra debugging info. I'll need your log file afterwards.

@Blazeflack, really? That's honestly an unexpected behaviour. Firstly because I expected it to print either *XButton1* or *XButton2*; secondly because if they are indeed recognised as mouse buttons they should theoretically not work if more than 2 of them are used in different hotkeys.
For example, let's say you bind *"Ctrl+D1"* to *VolumeUp* and *"Ctrl+D2"* to *VolumeDown*; then you try to bind *"Ctrl+D#"* (where # is 3 to 7) to *Mute*. I'd expect one of the following behaviours:
- Toastify says that the hotkey is already used.
- It binds correctly, but when you try to use that hotkey, it doesn't work or it triggers either or also *VolumeUp* or *VolumeDown*.
That's because Windows APIs only support up to 5 mouse buttons. The extra buttons must be handled by custom drivers. What I guess it's happening is that all or part of you side buttons are instead being interpreted as keyboard events.

**Comment by Blazeflack** [comment]
I just tested it again and all of my 7 side buttons appear to work fine as keybinds. I had volume up and down bound to D2 and D3, and I then bound D1 to Mute. I opened the volume mixer to keep an eye on the slider and when I pressed the Mute keybind it correctly muted the Spotify mixer and it did not modify the volume slider.

**Comment by gahujipo** [comment]
Sorry, my fault. All I had to do is change a setting in my Logitech SetPoint Control Panel which prevented the click event from being forwarded to Toastify. The setting is: 
![image](https://user-images.githubusercontent.com/26710574/37196213-48df7c32-2376-11e8-9d28-86ca360279be.png)

Now it works as expected. A big thank you from my side too for maintaining the project.
