### ISSUE TITLE
Spotify not available 

### ISSUE THREAD

**Issue by Suripurasu** [aleab/toastify#37]
After downloading the latest version whenever I try to use my hot keys it tells me "Spotify not available!". I've reinstalled both programs numerous times and the problem still persists. However even though it says "Spotify not available" it still launches it when I start Toastify.

There's no log file for me to attach unfortunately.

**Comment by clarkycal** [comment]
Refer to this issue, sounds similar to what i had, https://github.com/aleab/toastify/issues/35

**Comment by aleab** [comment]
First things first.
1. What version of Windows are you using?
2. What version of Spotify are you using?
3. Are you 100% sure that there are no log files anywhere? There should be log files in the following locations:
   - *"C:\Users\\{UserName}\AppData\Local\Toastify"* (I just need *"Toastify.log"*)
   - In the installation directory: *"C:\Program Files\Toastify"*
4. Does it happen when you launch Toastify **after** Spotify has been launched or **before**? In other words: is Spotify running when you launch Toastify?

**Comment by Suripurasu** [comment]
Windows 10 Home 64 bit
Version 1.0.75.483.g7ff4a0dc
I've tried both but I currently have the standard version installed
[Toastify.log](https://github.com/aleab/toastify/files/1794268/Toastify.log) Wasn't there when I originally made the post, Sorry.
I always launch Toastify first

**Comment by aleab** [comment]
I'll provide you with a test version with some extra debugging info enabled tomorrow. I'll need your log file again after you tested it. Stay tuned.

**Comment by aleab** [comment]
As promised, [here](https://github.com/aleab/toastify/files/1797890/ToastifyInstaller.zip)'s the test version.
In addition to the log file I'll also need every file inside _"C:\Users\\{UserName}\AppData\\**Roaming**\Toastify"_ (there should be either one or two files).

**Comment by Suripurasu** [comment]
I can't be certain but I don't think my log file has been updated since my original posting.

[Toastify.log](https://github.com/aleab/toastify/files/1798268/Toastify.log)
[ToastifyXML.zip](https://github.com/aleab/toastify/files/1798273/ToastifyXML.zip)

**Comment by aleab** [comment]
It didn't in fact. That's odd!
Try this:
- Uninstall Toastify
- Remove the following directories:
  * _"C:\Users\\{UserName}\AppData\\**Roaming**\Toastify"_
  * _"C:\Users\\{UserName}\AppData\\**Local**\Toastify"_
- Re-install the test version I uploaded earlier and retry

**Comment by Suripurasu** [comment]
I went through and deleted everything to do with Toastify and reinstalled once again and now it's working. Not sure what was going on but I think I had an older version that was somehow still installed that causing issues. 

[Toastify.zip](https://github.com/aleab/toastify/files/1798342/Toastify.zip)
[Toastify.log](https://github.com/aleab/toastify/files/1798343/Toastify.log)

**Comment by aleab** [comment]
Cool! I suspect that the old version the Settings file was causing problems. In the end removing that could have fixed the issue.

Did you update to my version straight from the original one (v1.8.3)? Or did you already use one of my previous releases?

**Comment by Suripurasu** [comment]
I had been using the original up until the latest update, That's when I found yours.

**Comment by aleab** [comment]
Alright! I'm glad your issue has been resolved.

By the way, I guess the latest official release works fine now, right?

**Comment by Suripurasu** [comment]
Yup, Everything is working great! Thanks!

**Comment by Vankog** [comment]
side note:
@aleab 
> Cool! I suspect that the old version the settings file was causing problems. In the end removing that could have fixed the issue.

This sounds like a decent possibility for an improvement suggestion. Some kind of migration or config check to make sure updates take care of configuration issues.

**Comment by aleab** [comment]
@Vankog

This is basically what happened in the last two weeks regarding the settings file:
- I switched from XML serialization to JSON serialization, because I needed to be able to populate default objects with deserialized data. The standard XML serializer doesn't provide this funcionality, but I knew Json.NET does, so I chose that library (b8bd253).
- I introduced a generic class ([`SettingValue<T>`](https://github.com/aleab/toastify/blob/master/Toastify/src/Model/SettingValue.cs)) to represent settings items, so that I could easily access default values, allowed values, etc. (**note**: `SettingValue<T>` is a nullable reference type; I probably should have made it a value type).
- I implemented an `XML -> JSON` migration, if the new *Toastify.cfg* is not found, but the old *Toastify.xml* exists ([here](https://github.com/aleab/toastify/blob/e0faf0e51b9eb833a915425b56e3e8d692d0181c/Toastify/src/App.xaml.cs#L188-L226)).
  It's not properly implemented, because it deserializes the XML file using the current settings names, instead of the names that were used before switching to JSON. However, this shouldn't cause any fatal problem in itself, because unrecognized settings are ignored ([here](https://github.com/aleab/toastify/blob/e0faf0e51b9eb833a915425b56e3e8d692d0181c/Toastify/src/Model/Settings.cs#L557-L579), line 576) and missing settings are filled with default values ([here](https://github.com/aleab/toastify/blob/e0faf0e51b9eb833a915425b56e3e8d692d0181c/Toastify/src/Model/Settings.cs#L557-L579), line 573).

Next week I'll probably do some more testing on this.

As usual, thank you very much for your suggestions! 😄👍

**Comment by trevtrevtrev** [comment]
Thanks for getting this new version out to us but I get the 'technical timeout' error. I see it from the logs its looking for external internet access which I need to send via a proxy. No proxy options in the Settings, are there some I can put in the .cfg file?

**Comment by aleab** [comment]
@trevtrevtrev, proxy settings are being worked on. See #46.
