### ISSUE TITLE
Volume Control

### ISSUE THREAD

**Issue by SK83RJOSH** [aleab/toastify#4]
I mostly use Toastify for the volume control, but the fact it uses the volume mixer has a few downsides.

Most notably I like I lose granular control over the volume, which is the case for anything that uses the volume mixer (curious if implementing something similar to Foobar's logarithmic volume control would help here?).

Not to mention the volume isn't reflected in Spotify itself, which is problematic since I use Spotify connect to control the volume at times as well.

I'm curious if you can't forward the default volume hotkey combo to Spotify via autohotkey (since you already use it for some things)?

Thanks!

**Comment by aleab** [comment]
Thanks for the feedback, Josh!
I must admit I didn't really look into the volume controls since I forked this project. 😅
Currently, I think it changes the mixer's volume in steps of 4 or 5%; it is indeed not a fine granularity, but Spotify uses a larger one itself (16 steps to go from 0% to 100%, with the Ctrl-Up hotkey, so it's ~6%); I can definitely change the granularity, though, or even turn it into a customizable setting.

Honestly, I know very little about audio in general, but I'm pretty sure Windows volume mixer is logarithmic as well, even if it doesn't let you control the decibel value directly. Teoretically, I think it is possible to dinamically (exponentially) change the granularity so that every volume change via hotkey causes a costant decibel change. However, IMHO I don't think that would help much.

As for changing the volume in Spotify, that is a fairly easy thing to implement with AutoHotkey. The problem, as I said, is that you are going to lose granularity as well.

I need to think about this. I might add an option in the settings to switch between Spotify volume control and Windows volume mixer.

Let me know what you think (and if I said something stupid 😳)

**Comment by SK83RJOSH** [comment]
Don't worry, nothing stupid there at all. In fact I might be the stupid one, because you're probably right about the volume control in Windows being logarithmic. 😄

Anyways, I think having an option for the step size as well as an option to forward the shortcut would be perfect for my use case. I think having in app volume control is the best solution ultimately, but I can see the step size being useful for others. I've honestly been tempted to hook into Spotify myself and write something to handle this, but maintaining that would be a nightmare. 😅 

By the way, thanks for forking this project -- I was happy to see it was still being actively developed by someone. 👍

**Comment by aleab** [comment]
I've release a new version with all the mentioned changes.

Unfortunately, I had to replace AutoHotkey with the good old SendMessage and PostMessage native methods and a bit of *hacks*, so the new *shortcut injection* system might break in the future.
The reason behind this choice, is that I didn't manage to get AutoHotkey send the key presses to Spotify if it is minimized. For now, the new system works flawlessly, though.

Thanks for the feedback, Josh. 👍

**Comment by SK83RJOSH** [comment]
Thanks so much, this resolve the issues on my end -- and yeah based on those commits, it seems like this was a "fun" one. 😄

**Comment by aleab** [comment]
As expected, the *hacky* way at the base of this functionality doesn't work anymore with the latest release of Spotify (v1.0.75.483.g7ff4a0dc). From the next release (v1.10.3), Toastify won't be able to control Spotify's in-app volume.

See 9cb83d1 and the referenced issue for details.

**Comment by Vankog** [comment]
I am a little bit confused about the issue at hand:
![volume](https://user-images.githubusercontent.com/3804909/37208790-e6983f0a-23a2-11e8-8eff-08b53671fc32.png)

Isn't this option what you are looking for?

**Comment by aleab** [comment]
Hello there @Vankog!

I am confused now. Did you update to the latest release of Toastify yet? That *Spotify* option should definitely not be there anymore! 😕

**Comment by Vankog** [comment]
Nope, was just contemplating about the issue. Will update in a bit.

BTW: Just saw the other issues that the volume control is affected by the new menu layout. So my comment is obsolete anyway ;-)
