### ISSUE TITLE
Toast is not presented when toastify is "minimized to progress bar"

### ISSUE THREAD

**Issue by Capiz** [aleab/toastify#44]
Hi there

the toast is not presented when hotkey is pressed, even though my settings says so.
If toastify is present, the toast is "always on".
I can "show/hide" toast via hotkey, crtl+alt+space, but i would like it to show when new song is playing, next/prev song, play/pause.
Normally it was possible to have opacity, this is not possible anymore.
Could be awesome to have these features back to toastify - mostly, im just thankfull for having toastify back :-)

**Comment by aleab** [comment]
Hi @Capiz!

Let's see if I understood correctly.

You have the *"Only show Toast when Hotkey is pressed"* option enabled (in the *Toast* tab of the settings) and the toast only shows up when you press the *Show/Hide Toast* hotkey. That's the expected behaviour.

If you disable the *"Only show Toast when Hotkey is pressed"* option, it will also pop up when the song changes (automatically, or by pressing the *Next/Previous Song* hotkey). If it doesn't, that's a bug.

I agree that currently the settings do a really bad job at explaining it. I need to work on it.

> Normally it was possible to have opacity, this is not possible anymore.

Do you mean color opacity? It's still possible; I just moved the control (which was a separate control previously) into the color itself. So you can also change the transparency/opacity when you modify the color: it's the A channel.

**Comment by Capiz** [comment]
Awesome fast return on this thread... Thanks a million... Case cloased... everything worked like a charm :-)
