### ISSUE TITLE
Hotkey to open Spotify not working

### ISSUE THREAD

**Issue by uluo** [aleab/toastify#48]
I am unable to open Spotify using Toast hotkeys. It was originally mapped as Ctrl+Shift+Down, and worked before Toastify was broken with Spotify's latest update. I've tried different mappings, but none of them work, so it shouldn't be an issue of hotkey combinations.

Any idea if this can be fixed? It's quite useful to use the hotkey to bring Spotify up. I usually have it hidden on my taskbar.

**Comment by aleab** [comment]
Hi @uluo!

By *taskbar* you mean the area in bottom left corner or the one in the bottom right corner, near the system clock?
The one on the left is called taskbar, the one on the right is called system tray bar/area. The *"Show/Hide Spotify"* action only works for the taskbar since the latest update, unfortunately.

**Comment by uluo** [comment]
Oops! I did mean the system tray. And you're right in that the hotkey only works if Spotify is on my _taskbar_, I'll just have to make do with that for now. Thanks for the help!
