### ISSUE TITLE
Global Volume Control 

### ISSUE THREAD

**Issue by JackyOreo** [aleab/toastify#69]
## EXPECTED BEHAVIOUR
Toastify pops up with 'volume up/down' and adjusts the volume of spotify alone.

## ACTUAL BEHAVIOUR
Toestify pops up with 'volume up/down', but doesn't change the volume of spotify. 

## STEPS TO REPRODUCE THE BEHAVIOUR
Use volume rocker on keyboard.

## LOG FILE
[Toastify.log](https://github.com/aleab/toastify/files/1879256/Toastify.log)

**Comment by aleab** [comment]
Hi @JackyOreo!
The actual expected behaviour would be to change the global volume in the Windows Volume Mixer, not Spotify's. If you want to change only Spotify's volume (in the mixer) you'd have to use the *"Windows Volume Mixer (Spotify)"* option.
Currently Toastify can't change the internal volume of Spotify, but only the app's volume in the Windows mixer.

Also, the media keys on your keyboard will retain their default behaviour if they are not specifically set as hotkeys in Toastify. So, your volume keys will still change Windows volume even if you use the option mentioned above.

**Comment by JackyOreo** [comment]
Hi,
Thanks for the quick answer. I changed the hotkeys to my mediakeys so that works perfectly, though I didn't know it changes the mixers volume of the program, everthing works fine then. I just had to change the volume increments and now I can hear the difference in volume. Awesome program, it helps a ton.
Kind regards,
Jacky

**Comment by aleab** [comment]
Yeah, I should probably increase the default volume increment value a bit; it causes quite some confusion, I reckon.

Enjoy your music!! :smile:
