### ISSUE TITLE
[Feature Request] Thumbs Up/Down Support

### ISSUE THREAD

**Issue by Justinzobel** [aleab/toastify#7]
Would be good to be able to thumbs up/down from keyboard through Toastify.

**Comment by aleab** [comment]
Hi Justinzobel.
Unfortunately, there's no easy and non-invasive way to do that.

I'll explain it briefly.
Toastify communicates with Spotify by sending *messages* to its window. These messages can either be simple key presses (media keys or [shortcuts provided by Spotify](https://support.spotify.com/us/using_spotify/system_settings/keyboard-shortcuts)) or more complex messages sent to one of the window's components, namely the menu items (the ones in the top menu bar).
Optionally, I could also send requests to one of the endpoints of the [Web APIs](https://developer.spotify.com/web-api/endpoint-reference) (for now, none of the features of Toastify strictly requires it).

The problem is that the *Thumbs Up/Down* feature does not have a keyboard shortcut I can send to the window, nor does it have a menu item I can send a message to.
Moreover, there is no endpoint in the Web APIs that can do that either.

Also, the buttons you use in Spotify to *Thumbs Up/Down* are not proper components of the window, but items of an embedded Chrome view, so I cannot send native messages to them.
The only possible solution is to use something to get access to that view and *navigate* it. This solution was already implemented by nachmore (the original owner of the project) but it was removed because of performance issues (see [his post](https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Hotkey-for-Thumbs-up-or-down/td-p/605760#messageview_7)).

**Comment by Justinzobel** [comment]
Many thanks for the detailed response, I understand the complexities of it now and agree that it sounds like a complete PITA to implement. I just wish there was more native apps for Spotify that we could hack on to do what we want. I'm only moving to Spotify because Pandora retracted the service from my country (Australia) and using a VPN to negate the geo-blocking is just a PITA.
