### ISSUE TITLE
Toastify crashes when entering Proxy settings

### ISSUE THREAD

**Issue by brazilian812** [aleab/toastify#73]
My Spotify at work goes through a HTTPS proxy.  I enter the proxy info on the Toastify pop-up, my Spotify? login/password, and Toastify crashes with the following log.  Win8.1 Enterprise, Toastify 1.10.8.6157.  I did uninstall old Toastify with Revo, deleted the recommended files, and installed this fork of Toastify. 

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	Toastify.exe
  Problem Signature 02:	1.10.8.6157
  Problem Signature 03:	5ac1867a
  Problem Signature 04:	Toastify
  Problem Signature 05:	1.10.8.6157
  Problem Signature 06:	5ac1867a
  Problem Signature 07:	48
  Problem Signature 08:	0
  Problem Signature 09:	System.NullReferenceException
  OS Version:	6.3.9600.2.0.0.256.4
  Locale ID:	1033
  Additional Information 1:	1763
  Additional Information 2:	17639ad8f48a49cf26b3ff535776e42d
  Additional Information 3:	d991
  Additional Information 4:	d99168fbf6cd44a2d3849873ebd9d419

**Comment by aleab** [comment]
Can you post your latest log file? It's in *C:\Users\\{UserName}\AppData\Local\Toastify*.

**Comment by brazilian812** [comment]
[Toastify.log](https://github.com/aleab/toastify/files/1948200/Toastify.log)

Here you go. The log implies that it couldn't connect to the proxy, but the address listed (with port 80) isn't what I enter in the proxy settings, just FYI.  Should I be hitting 'Close' or 'Reset' in the proxy settings window?

**Comment by aleab** [comment]
@brazilian812, sorry for my delayed response.

The answer to your question is 'Close'.

Anyway, the proxy support is still pretty new in Toastify and mostly not thoroughly tested; for example it still doesn't support Sock proxies and I'm not 100% sure it supports HTTPS ones either.

I'd like to debug this issue further, though. Can you follow a couple of steps for me?

1. Head over to *"C:\Users\\{UserName}\AppData\Roaming\Toastify"* and either:
    1. Remove the *"Toastify.cfg"* file, only if you don't care about losing your settings, or
    2. Open the *"Toastify.cfg"* file with the notepad and remove the "UseProxy" and "ProxyConfig" settings.
      You'll have something like the following; remove the "UseProxy" line and the "ProxyConfig" block (the line itself + the lines between the curly braces, included the line the closed curly brace is in).
```json
"SongProgressBarForegroundColor": "#FFA0A0A0",
"UseProxy": true,
"ProxyConfig": {
  "Host": "104.154.127.47",
  "Port": 80,
  "Username": "probably a username",
  "BypassProxyOnLocal": true
},
"PreviousVersion": "1.10.8",
```

So that you'll end up with only:
```json
"SongProgressBarForegroundColor": "#FFA0A0A0",
"PreviousVersion": "1.10.8",
```

2. Go to *"C:\Users\\{UserName}\AppData\Local\Toastify"* and remove the *"proxy.sec"* file, if it exists, and every log file.

3. Start Toastify from the command line with the "--debug" option. This will make Toastify print extra debugging info in the log.
    Alternatively, you can also install this version: [ToastifyInstaller.zip](https://github.com/aleab/toastify/files/1949168/ToastifyInstaller.zip), which is the current build I'm working on with the extra debug info enabled by default (so you won't need to do step 3 if you install this).

    To start Toastify from the command line, follow these steps. Let's say you installed Toastify to *"C:\Program Files\Toastify"*; then:
    1. Press *Windows Key + R*, type `cmd` in the *"Run"* dialog window that popped up and hit enter.
    2. Execute the following commands one after the other:
        - `cd /d "C:\Program Files\Toastify"`
        - `Toastify.exe --debug`

4. Post your log file after Toastify crashes.

**Comment by brazilian812** [comment]
Very strange.  So Toastify asks if I am behind a proxy, I say Yes, and it opens the window to enter my proxy details.  I enter them, click 'Close' and Toastify immediately crashes and I get Window's "Toastify has stopped working" window.  I click 'Close the program' and Windows pops up with another "Toastify has stopped working" window.  I click 'Close the program' again, it is gone, and I am left with the log I posted, the one that seems to end prematurely

**Comment by brazilian812** [comment]
[eventvwr.log](https://github.com/aleab/toastify/files/1952089/eventvwr.log)

**Comment by aleab** [comment]
Alright, I think I'm on to something, but first I would like to take a look at some file located in *"C:\Users\jtnovack\AppData\Local\Microsoft\Windows\WER\ReportArchive"*; namely *"AppCrash_Toastify.exe_18a2c7246b9c2deb274d5ca39643d70127b6bb1_b4d4029f_3805de8c"*.
If you can't find that file specifically, any file that begins with *"AppCrash_Toastify.exe_"* is fine.
That is a detailed report from the Windows Error Reporting utility; it might contain some more information.

To post that file here, you might need to put it in a zip file first or change its extension to "txt" or "log".

---

I think the problem is a corrupt or incomplete installation of the .NET Framework.
[Here](https://www.microsoft.com/net/download/all) you'll find most of the .NET Framework installers; please, install *".NET Framework 4.5.2"* and, although not needed, *".NET Framework 3.5 SP1"*. Then restart your PC and try starting Toastify again, possibly from the command line with the "--debug" option.

**Comment by brazilian812** [comment]
[ReportArchive.zip](https://github.com/aleab/toastify/files/1952198/ReportArchive.zip)

The reports come in pairs (probably since Windows gives me two crash windows) so here is the latest pair from this morning

**Comment by aleab** [comment]
Unfortunately the reports didn't provide any new information.

Please, try to (re-)install the .NET Framework as I said in my previous post. In the meantime I'll try to test the application in a Windows 8.1 virtual machine to rule out a possible compatibility problem.
