### ISSUE TITLE
Startup error ("An error occurred when trying to start Spotify"), leading to no toast notifications

### ISSUE THREAD

**Issue by PaulLFC** [aleab/toastify#8]
I recently downloaded Toastify on Windows 10 Pro x64, but I cannot seem to get it to run with Spotify. When the two programs are started, after around 5 seconds Toastify will pop up an error message:

"An error occurred when trying to start Spotify

Technical details
Spotify is running: true
Status: null

Additional details
An error occurred when trying to start Spotify: Toastify was not able to connect with Spotify."

Toastify will then keep running but is unable to display any toast notifications. This state happens both when starting Toastify first (letting it launch Spotify itself), and when launching Spotify manually, and then Toastify after.

I have tried a restart, and setting all of Spotify, SpotifyLauncher and Toastify to run as administrator. Unfortunately none of these have worked.

This is with Toastify 1.9.5, the desktop Windows Spotify program (not Windows Store version), 1.0.62.508.g2c497f24. Windows 10 Pro x64 v1703.

**Comment by aleab** [comment]
Hi PaulLFC!

Does it happen **every** time, or is it *random*?
It's strange, because it shouldn't happen when launching Spotify manually.

Unfortunately, I do not have the 1.0.62 version of Spotify yet, so I don't know if it's caused by a change in Spotify. I'll investigate and let you know in a couple of days, I think, maybe with a test build for you to try.

In the meantime you can try to change an hidden setting I've added some time ago. Open the `%USERPROFILE%\AppData\Roaming\Toastify\toastify.xml` file with the notepad, find the `SpotifyConnectionAttempts` setting and change its value (I think the default value is 5; try changing it to 10).

**Comment by PaulLFC** [comment]
Hi @aleab!
Thanks for the workaround, unfortunately it seems the issue is still present - it was set at 10 initially, so I switched to 20, and although this delays the error because of the extra attempts, it still shows eventually and prevents Toastify from interacting with Spotify.
Thanks for looking into this!

**Comment by aleab** [comment]
Can I ask you to zip your version of Spotify for me, so that I can try that out?
It's usually in `%USERPROFILE%\AppData\Roaming\Spotify`; remember to remove the `Users` directory and the `prefs` file from the zipped folder, they may contain private information.

Thanks!

**Comment by PaulLFC** [comment]
No problem, hopefully this link should work: [https://ufile.io/059p5](https://ufile.io/059p5)

**Comment by aleab** [comment]
As I suspected, the bug is caused by a change in the latest version of Spotify that broke one of the libraries used by Toastify ([this one](https://github.com/JohnnyCrazy/SpotifyAPI-NET)).
I'm currently waiting for the maintainer of that project to provide a hotfix. Unfortunately, I do not have an ETA on this nor an immediate fix.

**Comment by PaulLFC** [comment]
Thanks for the reply and for investigating this! Hopefully the author of the library will be able to fix the issue soon, from having a look at the project it seems he's aware of it and working on a fix, so fingers crossed it won't be broken for too much longer.

**Comment by aleab** [comment]
The [latest release](https://github.com/aleab/toastify/releases/latest) should fix your issue. Let me know if it doesn't.

**Comment by PaulLFC** [comment]
@aleab Latest release works perfectly! Connects to Spotify straight away with no errors and toasts appear correctly. Thanks for fixing this so quickly.
